---
minimum_pre_commit_version: 2.4.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # v6.0.0
    hooks:
      - id: check-merge-conflict   # Check for files that contain merge conflict strings.
        args: [--assume-in-merge]
      - id: trailing-whitespace    # Trim trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending      # Ensure files use UNIX-style newlines only.
        args: [--fix=lf]
      - id: end-of-file-fixer      # Ensure files end with a newline.
      - id: check-ast              # Check whether files parse as valid Python.

  # ----- Formatting ---------------------------------------------------------------------------->
  - repo: https://github.com/saltstack/pre-commit-remove-import-headers
    rev: 209beff8e11fed83f3f0863ccfd95aa663fffaf6  # 1.1.0
    hooks:
      - id: remove-import-headers

  - repo: local
    hooks:
      - id: check-cli-examples
        name: Check CLI examples on execution modules
        entry: python .pre-commit-hooks/check-cli-examples.py
        language: python
        files: ^src/saltext/vault/modules/.*\.py$

  - repo: local
    hooks:
      - id: check-docs
        name: Check rST doc files exist for modules/states
        entry: python .pre-commit-hooks/make-autodocs.py
        language: python
        pass_filenames: false

  - repo: https://github.com/saltstack/salt-rewrite
    # Automatically rewrite code with known rules
    rev: 8079cfb7f601e5dbad58b8449d85bb24f1e52082  # 2.5.2
    hooks:
      - id: salt-rewrite
        alias: rewrite-docstrings
        name: Salt extensions docstrings auto-fixes
        files: ^src/saltext/vault/.*\.py$
        args: [--silent]

  - repo: https://github.com/saltstack/salt-rewrite
    # Automatically rewrite code with known rules
    rev: 8079cfb7f601e5dbad58b8449d85bb24f1e52082  # 2.5.2
    hooks:
      - id: salt-rewrite
        alias: rewrite-tests
        name: Rewrite the test suite
        files: ^tests/.*\.py$
        args: [--silent, -E, fix_docstrings]

  - repo: https://github.com/asottile/pyupgrade
    rev: 75992aaa40730136014f34227e0135f63fc951b4  # v3.21.2
    hooks:
      - id: pyupgrade
        name: Rewrite Code to be Py3.10+
        args: [
          --py310-plus,
        ]
        exclude: src/saltext/vault/version.py

  - repo: https://github.com/PyCQA/isort
    rev: 0a09c783808cfe77bb3269250f663ff733d23302  # 7.0.0
    hooks:
      - id: isort
        args: [
          --py 310,
        ]
        exclude: src/saltext/vault/(__init__|version).py

  - repo: https://github.com/psf/black
    rev: 6305bf1ae645ab7541be4f5028a86239316178eb  # 26.1.0
    hooks:
      - id: black
        args: [-l 100]
        exclude: src/saltext/vault/version.py

  - repo: https://github.com/adamchainz/blacken-docs
    rev: dda8db18cfc68df532abf33b185ecd12d5b7b326  # 1.20.0
    hooks:
      - id: blacken-docs
        args: [--skip-errors]
        files: ^(docs/.*\.rst|src/saltext/vault/.*\.py)$
        additional_dependencies:
          - black==26.1.0
  # <---- Formatting -----------------------------------------------------------------------------

  # ----- Security ------------------------------------------------------------------------------>
  - repo: https://github.com/PyCQA/bandit
    rev: 765f00d3f202f83f61d03f882f80a2d5142d81f8  # 1.9.3
    hooks:
      - id: bandit
        alias: bandit-salt
        name: Run bandit against the code base
        args: [--silent, -lll, --skip, B701]
        exclude: src/saltext/vault/version.py

  - repo: https://github.com/PyCQA/bandit
    rev: 765f00d3f202f83f61d03f882f80a2d5142d81f8  # 1.9.3
    hooks:
      - id: bandit
        alias: bandit-tests
        name: Run bandit against the test suite
        args: [--silent, -lll, --skip, B701]
        files: ^tests/.*
  # <---- Security -------------------------------------------------------------------------------

  # ----- Code Analysis ------------------------------------------------------------------------->

  - repo: local
    hooks:
      - id: nox
        alias: lint-src
        name: Lint Source Code
        language: python
        entry: nox -e lint-code-pre-commit --
        files: ^((setup|noxfile)|src/.*)\.py$
        require_serial: true
        additional_dependencies:
          - nox==2025.11.12
          - uv==0.9.27  # Makes this hook much faster

      - id: nox
        alias: lint-tests
        name: Lint Tests
        language: python
        entry: nox -e lint-tests-pre-commit --
        files: ^tests/.*\.py$
        require_serial: true
        additional_dependencies:
          - nox==2025.11.12
          - uv==0.9.27  # Makes this hook much faster

  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: 85c37735ea69e5baf0681530e57e63deee0ce733  # v1.7.10.24
    hooks:
      - id: actionlint
        additional_dependencies:
          - shellcheck-py==0.11.0.1
  # <---- Code Analysis --------------------------------------------------------------------------
