---
name: Publish Documentation

on:
  workflow_call:
    inputs:
      # This is the name of the regular artifact that should
      # be transformed into a GitHub Pages deployment.
      artifact-name:
        type: string
        required: false
        default: html-docs

jobs:

  # The released docs are not versioned currently, only the latest ones are deployed.
  #
  # Versioning support would require either (better):
  #   * Rebuilding docs for all versions when a new release is made
  #   * Version selector support in `furo`: https://github.com/pradyunsg/furo/pull/500
  #
  # or (more basic):
  #   * using the `gh-pages` branch and peaceiris/actions-gh-pages
  #     to be able to deploy to subdirectories. The implementation via
  #     actions/deploy-pages always replaces the directory root.

  Deploy-Docs-GH-Pages:
    name: Publish Docs to GitHub Pages

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-24.04

    steps:
      - name: Download built docs
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131  # v7.0.0
        with:
          name: ${{ inputs.artifact-name }}
          path: html-docs

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b  # v4.0.0
        with:
          name: html-docs-pages
          path: html-docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e  # v4.0.5
        with:
          artifact_name: html-docs-pages

      - name: Delete GitHub Pages artifact
        if: always()
        uses: geekyeggo/delete-artifact@7ee91e82b4a7f3339cd8b14beace3d826a2aac39  # v5.1.0
        with:
          name: html-docs-pages
          failOnError: false

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6.0.0
        with:
          name: exitstatus-${{ github.job }}
          path: exitstatus
          if-no-files-found: error
